### ISSUE TITLE
To-Do verif mise en ligne

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/rf-departementales-2015#44]
* [ ] Code Google analytics
* [ ] Code Xiti remonte bien
* [ ] Verif embed page définitive
